package com.leads.capita.account
import kotlinx.serialization.Serializable
@Serializable
class AccountBalance(
    var accountCode: String = "",
    var accruedCharge: Double = 0.0,
    var assetValue: Double = 0.0,
    var buyingPower: Double = 0.0,
    var cashBalance: Double = 0.0,
    var costValue: Double = 0.0,
    var currentBalance: Double = 0.0,
    var deposit: Double = 0.0,
    var deptEquityRatio: Double = 0.0,
    var dividendIncome: Double = 0.0,
    var dividendReceivable: Double = 0.0,
    var equity: Double = 0.0,
    var equityDebtRatio: Double = 0.0,
    var fundTransIn: Double = 0.0,
    var fundTransOut: Double = 0.0,
    var fundWithdrawalRequest: Double = 0.0,
    var immatureBalance: Double = 0.0,
    var instrumentTransIn: Double = 0.0,
    var instrumentTransOut: Double = 0.0,
    var ipoApplication: Double = 0.0,
    var loanRatio: Double = 0.0,
    var marginEquity: Double = 0.0,
    var marketValue: Double = 0.0,
    var maxLoan: Double = 0.0,
    var netDepositWithdraw: Double = 0.0,
    var netGainLoss: Double = 0.0,
    var preIpoApplication: Double = 0.0,
    var preferenceApplication: Double = 0.0,
    var realiseGainLoss: Double = 0.0,
    var rightApplication: Double = 0.0,
    var rightOrder: Double = 0.0,
    var totalDeposit: Double = 0.0,
    var totalWithdrawal: Double = 0.0,
    var unclearCheque: Double = 0.0,
    var unrealiseGainLoss: Double = 0.0,
    var withdrawal: Double = 0.0
)

